theme: jekyll-theme-cayman

markdown: kramdown

#baseurl: /RealADSim
baseurl: /2025

# Remove `View on GitHub` & Download buttons
show_downloads: false
#github:
#  is_project_page: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jemoji
  - jekyll-remote-theme