#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --url-ignore '/fonts.gstatic.com/' '/workshop_test/assets/css/style.css?v='
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-cayman.gemspec
